# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: windows-latest

steps:


- task: mirror-git-repository-vsts-task@1
  inputs:
    sourceGitRepositoryUri: 'https://github.com/HotCakeX/Harden-Windows-Security/'
    sourceGitRepositoryPersonalAccessToken: '$(GitPaT)'
    destinationGitRepositoryUri: 'https://dev.azure.com/SpyNetGirl/Harden-Windows-Security/'
    destinationGitRepositoryPersonalAccessToken: '$(AzurePaT)'