name: Bug Report 🐛
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - HotCakeX
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!  
  - type: dropdown
    id: version
    attributes:
      label: Tools category
      description: Which category/tool does this bug belong to?
      options:
        - Harden Windows Security Script
        - Harden Windows Security Module
        - WDACConfig Module
    validations:
      required: true 
  - type: checkboxes
    id: Requirements
    attributes:
      label: Does your system meet the requirements?
      description: Depending on which tool your bug belongs to, please make sure you have read their requirements and meet them [Harden Windows Security Requirements](https://github.com/HotCakeX/Harden-Windows-Security#requirements-), [WDACConfig Requirements](https://github.com/HotCakeX/Harden-Windows-Security/wiki/WDACConfig#requirements), [Harden Windows Security Module Requirements](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Harden%E2%80%90Windows%E2%80%90Security%E2%80%90Module#requirements)
      options:
        - label: Yes, my system meets the requirements 👍
          required: true
  - type: textarea
    id: Explanation
    attributes:
      label: Explain the bug
      description: Please explain the bug and be as detailed as possible. 🙏
      render: shell
    validations:
      required: true 
