name: Bug Report 🐛
description: File a bug report
title: "[Bug]: "
labels: ["Bug 🐛"]
assignees:
  - HotCakeX
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: version
    attributes:
      label: Tools category
      description: Which category/tool does this bug belong to?
      options:
        - Harden Windows Security Module
        - WDACConfig Module
    validations:
      required: true
  - type: checkboxes
    id: Requirements
    attributes:
      label: Does your system meet the requirements?
      description: Depending on which tool your bug belongs to, please make sure you have read their requirements and meet them [Harden Windows Security Requirements](https://github.com/HotCakeX/Harden-Windows-Security#requirements-), [WDACConfig Requirements](https://github.com/HotCakeX/Harden-Windows-Security/wiki/WDACConfig#requirements)
      options:
        - label: Yes, my system meets the requirements 👍
          required: true
  - type: checkboxes
    id: Genuine-Windows
    attributes:
      label: Is your Windows installation genuine?
      description: Genuine means you downloaded Windows installation media from the official Microsoft website and it is neither tampered nor modified by any 3rd party tools.
      options:
        - label: Yes, I am using genuine Windows installation and have not tampered with the OS files. 💯
          required: true
  - type: textarea
    id: Explanation
    attributes:
      label: Please explain the bug
      description: Please explain the bug and be as detailed as possible. 🙏
      placeholder: "There is a problem with..."
    validations:
      required: true
  - type: textarea
    id: Error-Details
    attributes:
      label: Error details
      description: Paste the output from `Get-Error` if PowerShell returned errors.
      render: console
      placeholder: PS> Get-Error