blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions ✍️
    url: https://github.com/HotCakeX/Harden-Windows-Security/discussions
    about: Please use GitHub discussions for any questions.
