name: Virus Total
on:
  push:
    paths:
      - Payload/**
  workflow_dispatch:

jobs:
  build:
    name: Run Script
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Script
        env:
          doh: ${{ secrets.doh }}
        shell: pwsh
        run: |
              $url = $env:doh              
              
              $IPs = curl --ssl-no-revoke --max-time 10 --tlsv1.3 --tls13-ciphers TLS_CHACHA20_POLY1305_SHA256 --http2 -H "accept: application/dns-json" "https://1.1.1.1/dns-query?name=$url&type=A"
              $IPs = ( $IPs | ConvertFrom-Json).answer.data

              $IPs | Out-File .\Workflowstuff\IPs.txt
            
            
            
            
