name: Virus Total
on:
  push:
    paths:
      - Payload/**
  workflow_dispatch:

jobs:
  build:
    name: Run Script
    runs-on: windows-latest
    # Add this line to prevent the job from running on a release
    if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v3
      - name: Script
        env:
          VTAPIsecret: ${{ secrets.VTAPI }}
        shell: pwsh
        run: |
            
            ./.github/Workflowstuff/VirusTotal
